### ISSUE TITLE
Commands defined in config/params.php are not available in vendor/bin/yii

### ISSUE THREAD

**Issue by goale** [yiisoft/yii-demo#105]
### What steps will reproduce the problem?
Run `./vendor/bin/yii` in terminal

### What is the expected result?

Commands defined in config/params.php should be in the command list
```
'console' => [
        'commands' => [
            'user/create' => Command\User\CreateCommand::class,
            'fixture/add' => Command\Fixture\AddCommand::class,
            'router/list' => Command\Router\ListCommand::class,
        ],
    ],
```

### What do you get instead?
![изображение](https://user-images.githubusercontent.com/4661017/84905952-030fe380-b0ba-11ea-857e-5acd1775eec6.png)

I believe that the problem is caused by the recent changes in config structure and `console` key should be `yiisoft/yii-console`.

### Additional info

| Q                | A
| ---------------- | ---
| Version          | dev
| PHP version      |  7.4.6
| Operating system | Debian 9 (docker)

**Comment by terabytesoftw** [comment]
thks.
