### ISSUE TITLE
App doesn't work from subfolder

### ISSUE THREAD

**Issue by alexkart** [yiisoft/yii-demo#11]
The documentation says

> The application installed according to the above instructions should work out of the box with either an Apache HTTP server or an Nginx HTTP server

### What steps will reproduce the problem?
Steps from the guide (https://github.com/yiisoft/docs/blob/master/guide/en/start/installation.md):

```bash
cd /var/www/html
composer create-project --prefer-dist --stability=dev yiisoft/yii-demo yii3-app
```
Apache virtualhost `DocumentRoot` is `/var/www/html`

Go to `http://server-name.test/yii3-app/public/`

You will see `We were unable to find the page /yii3-app/public/.`

### What is the expected result?
Work out of the box

### What do you get instead?
We were unable to find the page /yii3-app/public/.

### Additional info
If a separate virtual host is configured for the app as explained further in the documentation it works as expected.

| Q                | A
| ---------------- | ---
| Version          | dev
| PHP version      | 7.3
| Operating system | Ubuntu 18.04

**Comment by samdark** [comment]
Is it typical to run the app via subfolder?

**Comment by alexkart** [comment]
In productions, of course not, but for testing purposes (like it's said in the docs "if you are just-test driving Yii") maybe yes.
I don't know what was the design decision and whether it is a bug or not? If it's correct behavior, so the documentation needs to be adjusted. "The application installed according to the above instructions should work out of the box" phrase should be removed and it should be mentioned that configuring a separate virtual host for the app is necessary.

**Comment by samdark** [comment]
Well, since Yii 2 worked well with this setup, I think we can consider it being a bug.

**Comment by SOHELAHMED7** [comment]
I tried to fix this issue but found that third arg in https://github.com/yiisoft/yii-demo/blob/master/src/Factory/MiddlewareDispatcherFactory.php#L22 is not present and hence 

https://github.com/yiisoft/yii-web/blob/master/src/MiddlewareDispatcher.php#L51 will always set to `NotFoundHandler`

and also https://github.com/yiisoft/yii-web/blob/master/src/MiddlewareDispatcher.php#L72 will always be true when all middleware are added.


As the docs and framework is in WIP state, I was not able to completely fix the issue but my thought are (that might be incorrect):

 -  Add 3rd argument to https://github.com/yiisoft/yii-demo/blob/master/src/Factory/MiddlewareDispatcherFactory.php#L22
 -  Change the logic of `isLastMiddlewareCalled`

**Comment by samdark** [comment]
> third arg in https://github.com/yiisoft/yii-demo/blob/master/src/Factory/MiddlewareDispatcherFactory.php#L22 is not present and hence
>
> https://github.com/yiisoft/yii-web/blob/master/src/MiddlewareDispatcher.php#L51 will always set to NotFoundHandler

That's intended. We don't want to change this default.

> https://github.com/yiisoft/yii-web/blob/master/src/MiddlewareDispatcher.php#L72 will always be true when all middleware are added.

If you mean "processed", not "added" then it's true and it's intended. If you mean "added" then no, it will be false until all middlware are processed.

>  I was not able to completely fix the issue but my thought are (that might be incorrect)

So it helped in your case? If so, that's very interesting because I don't see how not working from a sub-directory is connected to middleware stack processing and default handler that is executed when there are no middleware left to process.

**Comment by SOHELAHMED7** [comment]
> So it helped in your case? 

Sorry. I am unable to understand what are you trying to ask. Can you  please elaborate?

> If so, that's very interesting because I don't see how not working from a sub-directory is connected to middleware stack processing and default handler that is executed when there are no middleware left to process.

that is exactly I am confused about. Initially I thought it's the apache issue. But later found that https://github.com/yiisoft/yii-web/blob/master/src/NotFoundHandler.php#L35 send the 404 response

Question: Once all middleware are added a response should be sent but why in this case https://github.com/yiisoft/yii-web/blob/master/src/NotFoundHandler.php#L31 404  is sent?

**Comment by samdark** [comment]
> Sorry. I am unable to understand what are you trying to ask. Can you please elaborate?

Sure. I've meant to ask if you have tried to fix these two things you are pointing to and if yes, did it result in an application working from sub-directory?

**Comment by SOHELAHMED7** [comment]
I tried both

For 1st one : 

> Add 3rd argument to https://github.com/yiisoft/yii-demo/blob/master/src/Factory/MiddlewareDispatcherFactory.php#L22

I got no relavant class which I can put as third agr

I did find/search

`implements(.*)RequestHandlerInterface` using regex in Sublime text

 in entire folder including vendor dir, but didn't get relavant class. Somewhat relavant stuff found is 

```php
vendor/yiisoft/yii-web/src/Middleware/Chain.php:
   35      private function wrap(MiddlewareInterface $middleware, RequestHandlerInterface $handler): RequestHandlerInterface
   36      {
   37:         return new class($middleware, $handler) implements RequestHandlerInterface {
   38              private $middleware;
   39              private $handler;
```
 

For 2nd one :

> Change the logic of isLastMiddlewareCalled

got no success

tried few ways (trial and error)
instead got 

php error about  too many recurring/nested function calls (something about max limit is 256) in one of the attempt

**Comment by samdark** [comment]
OK. These two are **very unlikely** the reason for this issue.

**Comment by samdark** [comment]
@roxblnfk is on it.
