### ISSUE TITLE
composer install error

### ISSUE THREAD

**Issue by xshnjau** [yiisoft/yii-demo#121]
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 120 installs, 0 updates, 0 removals
  - Installing foxy/foxy (v1.1.0): Loading from cache
Plugin installation failed (No asset manager is found), rolling back
  - Removing foxy/foxy (v1.1.0)

                                     
[Foxy\Exception\RuntimeException]  
No asset manager is found

**Comment by yiiliveext** [comment]
You should install npm
