### ISSUE TITLE
Using of User and ActiveForm models

### ISSUE THREAD

**Issue by maximal** [yiisoft/yii-demo#13]
Could you please provide a brief example of User identity model and login form in this app?

**Comment by samdark** [comment]
User and identity are almost ready: https://github.com/yiisoft/yii-web/pull/101

**Comment by maximal** [comment]
@samdark, that’s brilliant!

**Comment by samdark** [comment]
Identity is done + login / logout added to demo.

**Comment by maximal** [comment]
Thank you!
