### ISSUE TITLE
Where is Models?

### ISSUE THREAD

**Issue by ingen2** [yiisoft/yii-demo#133]
Hi 

In the current structure, the models have been removed and replaced by repositories.

I think models should exist and do functional actions on repositories.

In this method, the Repository contain basic functions (such as finaAll , findOne, etc.) and the Model have the controller required functions.

Repository Example:

    class UserRepository extends ...
    {
        public function findAll(array $scope = [], array $orderBy = []): DataReaderInterface
        {
            return new SelectDataReader($this->select()->where($scope)->orderBy($orderBy));
        }

        private function findIdentityBy(string $field, string $value): ?IdentityInterface
        {
            return $this->findOne([$field => $value]);
        }

        public function findIdentity(string $id): ?IdentityInterface
        {
            return $this->findByPK($id);
        }

        public function findIdentityByToken(string $token, string $type = null): ?IdentityInterface
        {
            return $this->findIdentityBy('token', $token);
        }

        public function findByLogin(string $login): ?IdentityInterface
        {
            return $this->findIdentityBy('login', $login);
        }
    }

Model Example:

    class User extends Model
    {
        public function search(array $params = [],UserRepository $userRepository)
        {
            $dataReader = $userRepository->findAll()->withSort((new Sort([]))->withOrderString('login'));
            $paginator = (new OffsetPaginator($dataReader))
                ->withPageSize(self::PAGINATION_INDEX)
                ->withCurrentPage($pageNum);

            return $paginator;
        }
        

        public function signup(...)
        {
            //validate 
            //create user record
            //create user profile
            
        }

        public function ActiveUser(...)
        {
                
        }
    }

**Comment by samdark** [comment]
That's one of the approaches to work with database via Cylce ORM that is used in yii-demo. @terabytesoftw has ported database layer and Active Record as a separate package so it will be possible to have ARs as well.

What you have there is called "service" and there's no need to extend it from anything in Yii 3. See https://github.com/yiisoft/docs/blob/master/guide/en/structure/service.md
