### ISSUE TITLE
The console application does not work along the path ./vendor/bin/yii

### ISSUE THREAD

**Issue by AllanNP** [yiisoft/yii-demo#141]
### What steps will reproduce the problem?
The console application does not work along the path ./vendor/bin/yii
### What is the expected result?
The console application php vendor/yiisoft/yii-console/bin/yii
### What do you get instead?
/usr/bin/env: 'php\r': No such file or directory

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      |  7.4
| Operating system |
Windows yiisoftware/yii-php:7.4-apache  Docker conteiner

**Comment by samdark** [comment]
I guess `\r` may be a problem and changing it to `\n` may help.

**Comment by samdark** [comment]
@AllanNP how did you install the app? Using composer from Windows or using composer from a docker image?

**Comment by AllanNP** [comment]
Composer from a docker image.

**Comment by samdark** [comment]
Unable to reproduce it myself. @yiisoft/yii3 anyone with docker at hand, would you please try it?

**Comment by lusvlad** [comment]
Problem with windows line-ending. For local-fix change in editor `vendor/yiisoft/yii-console/bin/yii` CRLF to LF
