### ISSUE TITLE
Minor issue: InvalidArgumentException - Invalid path alias @web

### ISSUE THREAD

**Issue by rossaddison** [yiisoft/yii-demo#153]
### What steps will reproduce the problem?
Exclude `'@web'=>'@root/public'`, from 
```php
    'aliases' => [
            '@root' => dirname(__DIR__),
            '@views' => '@root/views',
            '@resources' => '@root/resources',
            '@src' => '@root/src',
           //'@web'=>'@root/public',
    ],
```
situated in file: `..config/params.php`

### What is the expected result?
Clean boot

### What do you get instead?
Above error.

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 3
| PHP version      | 7.49
| Operating system | Windows 10

**Comment by samdark** [comment]
Would you please provide a stacktrace?

**Comment by samdark** [comment]
`@web` was recently renamed into `@baseUrl`, it may be a leftover.

**Comment by samdark** [comment]
Checked that current `yii-demo` code works. Please do `git pull && composer update`.

**Comment by rossaddison** [comment]
As requested stack trace after composer has been updated:

InvalidArgumentException: Invalid path alias: @web in C:\wamp64\www\yii3demo\vendor\yiisoft\aliases\src\Aliases.php:149
Stack trace:
#0 C:\wamp64\www\yii3demo\vendor\yiisoft\assets\src\AssetPublisher.php(516): Yiisoft\Aliases\Aliases->get('@web')
#1 C:\wamp64\www\yii3demo\vendor\yiisoft\assets\src\AssetPublisher.php(221): Yiisoft\Assets\AssetPublisher->checkBaseUrl('@web')
#2 C:\wamp64\www\yii3demo\vendor\yiisoft\assets\src\AssetManager.php(94): Yiisoft\Assets\AssetPublisher->loadBundle('App\\Asset\\AppAs...', Array)
#3 C:\wamp64\www\yii3demo\vendor\yiisoft\assets\src\AssetManager.php(341): Yiisoft\Assets\AssetManager->getBundle('App\\Asset\\AppAs...')
#4 C:\wamp64\www\yii3demo\vendor\yiisoft\assets\src\AssetManager.php(192): Yiisoft\Assets\AssetManager->registerAssetBundle('App\\Asset\\AppAs...', NULL)
#5 C:\wamp64\www\yii3demo\views\layout\main.php(24): Yiisoft\Assets\AssetManager->register(Array)
#6 C:\wamp64\www\yii3demo\vendor\yiisoft\view\src\PhpTemplateRenderer.php(13): require('C:\\wamp64\\www\\y...')
#7 C:\wamp64\www\yii3demo\vendor\yiisoft\view\src\PhpTemplateRenderer.php(20): Yiisoft\View\PhpTemplateRenderer->Yiisoft\View\{closure}('C:\\wamp64\\www\\y...', Array)
#8 C:\wamp64\www\yii3demo\vendor\yiisoft\view\src\View.php(341): Yiisoft\View\PhpTemplateRenderer->render(Object(Yiisoft\View\WebView), 'C:\\wamp64\\www\\y...', Array)
#9 C:\wamp64\www\yii3demo\vendor\yiisoft\yii-view\src\ViewRenderer.php(166): Yiisoft\View\View->renderFile('C:\\wamp64\\www\\y...', Array, Object(Yiisoft\Yii\View\ViewRenderer))
#10 C:\wamp64\www\yii3demo\vendor\yiisoft\yii-view\src\ViewRenderer.php(60): Yiisoft\Yii\View\ViewRenderer->renderProxy('index', Array)
#11 C:\wamp64\www\yii3demo\vendor\yiisoft\data-response\src\DataResponse.php(163): Yiisoft\Yii\View\ViewRenderer->Yiisoft\Yii\View\{closure}()
#12 C:\wamp64\www\yii3demo\vendor\yiisoft\data-response\src\Formatter\HtmlDataResponseFormatter.php(29): Yiisoft\DataResponse\DataResponse->getData()
#13 C:\wamp64\www\yii3demo\vendor\yiisoft\data-response\src\DataResponse.php(170): Yiisoft\DataResponse\Formatter\HtmlDataResponseFormatter->format(Object(Yiisoft\DataResponse\DataResponse))
#14 C:\wamp64\www\yii3demo\vendor\yiisoft\data-response\src\DataResponse.php(40): Yiisoft\DataResponse\DataResponse->formatResponse()
#15 C:\wamp64\www\yii3demo\vendor\yiisoft\yii-web\src\SapiEmitter.php(101): Yiisoft\DataResponse\DataResponse->getBody()
#16 C:\wamp64\www\yii3demo\vendor\yiisoft\yii-web\src\SapiEmitter.php(40): Yiisoft\Yii\Web\SapiEmitter->shouldOutputBody(Object(Yiisoft\DataResponse\DataResponse))
#17 C:\wamp64\www\yii3demo\public\index.php(32): Yiisoft\Yii\Web\SapiEmitter->emit(Object(Yiisoft\DataResponse\DataResponse), false)
#18 {main}

Sent from Mail for Windows 10

**Comment by samdark** [comment]
You need to `git pull`, the stacktrace points to https://github.com/yiisoft/yii-demo/blob/master/src/Asset/AppAsset.php#L13 that is now `@baseUrl`, not `@app`.

**Comment by rossaddison** [comment]
Thanks yes without the git pull my line 13 says:

public ?string $baseUrl = '@web';

as opposed to:

public ?string $baseUrl = '@baseUrl';
