### ISSUE TITLE
 Error Interface 'Psr\Http\Message\ResponseFactoryInterface' not found

### ISSUE THREAD

**Issue by eresik** [yiisoft/yii-demo#174]
Error
Interface 'Psr\Http\Message\ResponseFactoryInterface' not found

At file vendor\httpsoft\http-message\src\ResponseFactory.php

**Comment by samdark** [comment]
Yes. That's https://github.com/composer/composer/issues/9490. For now, use Composer 1: `composer self-update --1`.

**Comment by samdark** [comment]
Fixed for now.
