### ISSUE TITLE
Installation error with PHP 8 in Ubuntu 20.04

### ISSUE THREAD

**Issue by akshay-vanjare** [yiisoft/yii-demo#182]
### What steps will reproduce the problem?
Installing demo from composer using command "composer install"

### What is the expected result?
Composer installed the demo with all the dependencies.

### What do you get instead?
Php version dependency error as below:

>   Problem 1
>     - Installation request for spatie/phpunit-watcher ^1.23 -> satisfiable by spatie/phpunit-watcher[1.23.0].
>     - spatie/phpunit-watcher 1.23.0 requires php ^7.2 -> your PHP version (8.0.0) does not satisfy that requirement.
>   Problem 2
>     - cycle/proxy-factory v1.2.2 requires php ^7.2 -> your PHP version (8.0.0) does not satisfy that requirement.
>     - cycle/proxy-factory v1.2.1 requires php ^7.2 -> your PHP version (8.0.0) does not satisfy that requirement.
>     - cycle/proxy-factory v1.2.0 requires php ^7.2 -> your PHP version (8.0.0) does not satisfy that requirement.
>     - Installation request for cycle/proxy-factory ^1.2 -> satisfiable by cycle/proxy-factory[v1.2.0, v1.2.1, v1.2.2].

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 8.0
| Operating system | Ubuntu 20.04

**Comment by samdark** [comment]
@xepozz constraint should be changed to dev-master@dev until there's a release with PHP 8.

**Comment by xepozz** [comment]
PHP 8 is already supported by constraint [see](https://github.com/spatie/phpunit-watcher/blob/1.23.1/composer.json#L19)

**Comment by xepozz** [comment]
As we found it happens with usage composer v1.

**Comment by xepozz** [comment]
Version of `spatie/phpunit-watcher` was forcely bumped to 1.23.1 that has supported PHP 8.
@akshay-vanjare can you please validate an error?

**Comment by samdark** [comment]
Seems it's alright now. Closing.
