### ISSUE TITLE
Best way to load params, proposal.

### ISSUE THREAD

**Issue by terabytesoftw** [yiisoft/yii-demo#19]
Controler.php

```php
abstract class Controller implements ViewContextInterface
{
    private $params;

    public function __construct()
    {
        $this->params = require dirname(__DIR__, 1) . '/config/params.php';
    }

    private function renderContent($content): string
    {
        $layout = $this->findLayoutFile($this->layout);
        if ($layout !== null) {
            return $this->view->renderFile($layout, ['content' => $content, 'params' => $this->params], $this);
        }

        return $content;
    }
}
```

What do you think, so it would be available for layouts and views, you could even use hiqdev-composer-plug-in to load all the params of the installed applications ?

| Q                | A
| ---------------- | ---
| Version          | 3.0
| PHP version      |  7.3.23
| Operating system | Windows10

**Comment by samdark** [comment]
Instead of controller we can create `Params` service with `get()` method and set it into container.

**Comment by terabytesoftw** [comment]
And how do we inject services params into layouts and views?

**Comment by samdark** [comment]
Either the way you have proposed or:

```php
public function actionX(ServerRequestInterface $request, Params $params): ResponseInterface
{
    // ...
    $this->view->setParameters(['name' => $params->get('name')]);
    // ...
}
```

**Comment by viktorprogger** [comment]
I'd prefer to manually inject `Params` service into a controller in which I want to see it. You may not use this service in your app at all, its necessity is contextual.
