### ISSUE TITLE
Add 404 fallback page

### ISSUE THREAD

**Issue by Mister-42** [yiisoft/yii-demo#192]
### What steps will reproduce the problem?
Visit a page that does not exist

### What is the expected result?
A nice 404 page. Bonus points for cats 😁 

### What do you get instead?
We were unable to find the page /x.

### Additional info

| Q                | A
| ---------------- | ---
| Version          | dev
| PHP version      | 7.4.13
| Operating system | Debian 10

**Comment by 1Luc1** [comment]
I'm interested in how to achieve this and played around a little bit with it. I came up with creating an own `NotFoundHandler` which implements the `RequestHandlerInterface`. This new Handler will be passed as `fallbackHandler` within the Application creation. May this the preferred way?

**Comment by samdark** [comment]
It was meant to be so. Is that convenient?

**Comment by samdark** [comment]
https://github.com/yiisoft/app/blob/master/config/web/application.php#L28

**Comment by 1Luc1** [comment]
I see, i see. I can make a PR?

**Comment by Mister-42** [comment]
> I see, i see. I can make a PR?

Yes, please 👍🏻
