### ISSUE TITLE
user console command not found

### ISSUE THREAD

**Issue by philippfrenzel** [yiisoft/yii-demo#194]
### What steps will reproduce the problem?
fresh install - git pull and composer update then yii user/create

### What is the expected result?
yii-console knows the command and creates a user

### What do you get instead?
command not known

### Additional info

| Q                | A
| ---------------- | ---
| Version          | dev
| PHP version      | 7.4
| Operating system | MAC

**Comment by samdark** [comment]
Fixed. Thanks.
