### ISSUE TITLE
User enumeration vulnerability

### ISSUE THREAD

**Issue by dzentota** [yiisoft/yii-demo#213]
### What steps will reproduce the problem?
Try to login with invalid login and/or password

### What is the expected result?
In case the user has specified invalid login OR password the error message must be the same, like `invalid user name or password`

### What do you get instead?
The application shows different errors 

```php
 /** @var \App\User\User $identity */
    $identity = $identityRepository->findByLogin($body['login']);
    if ($identity === null) {
        throw new \InvalidArgumentException('No such user');
    }

    if (!$identity->validatePassword($body['password'])) {
        throw new \InvalidArgumentException('Invalid password');
    }
```

**Comment by samdark** [comment]
Correct suggestion. Messages should be the same.
