### ISSUE TITLE
TypeError will browsing the Blog

### ISSUE THREAD

**Issue by numitec** [yiisoft/yii-demo#248]
### What steps will reproduce the problem?
Followed the Installation steps. Then, on Yii Demo (under apache), try the Blog.
### What is the expected result?
Show the entries of the Blog.
### What do you get instead?
Throws exception: Return value of App\Blog\Widget\PostCard::renderHead() must be of the type string, object returned

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 3.0.
| PHP version      | 7.4.14
| Operating system | Gentoo kernel-5.4.92

### Suggested fix
```
protected function renderHead(): string
{
    return (string) Html::a(
            Html::encode($this->post->getTitle()),
            $this->urlGenerator->generate('blog/post', ['slug' => $this->post->getSlug()]),
            ['class' => 'mb-0 h4 text-decoration-none'] // stretched-link
        );
}
```

**Comment by Mister-42** [comment]
protected function renderHead(): string
{
    return Html::a(
            Html::encode($this->post->getTitle()),
            $this->urlGenerator->generate('blog/post', ['slug' => $this->post->getSlug()]),
            ['class' => 'mb-0 h4 text-decoration-none'] // stretched-link
        )->render();
}

**Comment by numitec** [comment]
Thank you, Mister-42.

A little new suggest for fix in renderBody() method because it is showing the HTML code in author's link:

```
protected function renderBody(): string
{
        $return = Html::openTag('div');

        $return.= $this->post->getPublishedAt()->format('M, d');
        $return.= ' by '; 
        $return.= Html::a( 
                        Html::encode($this->post->getUser()->getLogin()),
                        $this->urlGenerator->generate('user/profile', ['login' => $this->post->getUser()->getLogin()]),
                        ['class' => 'mb-1 text-muted', 'encode' => false] 
                );
        $return.= Html::p(
                        Html::encode(mb_substr($this->post->getContent(), 0, 400))
                        . (mb_strlen($this->post->getContent()) > 400 ? '…' : ''),
                        ['class' => 'card-text mb-auto']
                );

        return $return . Html::closeTag('div');
}
```

**Comment by Mister-42** [comment]
Fair point, but https://github.com/Mister-42/yii-demo/commit/b7f95770f61b5b5f74b4d04ce93043a4a575815f is simpler

**Comment by numitec** [comment]
Brilliant!

**Comment by numitec** [comment]
Sorry to disturb you, Mister-42. I've tried your code (I've copied it from https://github.com/Mister-42/yii-demo/blob/b7f95770f61b5b5f74b4d04ce93043a4a575815f/src/Blog/Widget/PostCard.php):

```
protected function renderBody(): string
{
        return Html::div(
            $this->post->getPublishedAt()->format('M, d') . ' by ' . Html::a(
                $this->post->getUser()->getLogin(),
                $this->urlGenerator->generate('user/profile', ['login' => $this->post->getUser()->getLogin()])
            ),
            ['class' => 'mb-1 text-muted', 'encode' => false]
        ) . Html::p(
            mb_substr($this->post->getContent(), 0, 400)
            . (mb_strlen($this->post->getContent()) > 400 ? '…' : ''),
            ['class' => 'card-text mb-auto']
        );
}
```

  Perhaps I'm missing something but I'm getting again:

**Possimus non repudiandae explicabo ab in.**
Jan, 17 by &lt;a href="/user/Vince7532"&gt;Vince7532&lt;/a&gt;
_Alice. 'Only a thimble,' said Alice more boldly: 'you know you're growing too.'_

**Comment by Mister-42** [comment]
That's the trouble when not being able to test the code 🤣 Is [this](https://github.com/Mister-42/yii-demo/blob/patch-1/src/Blog/Widget/PostCard.php) better now?

**Comment by numitec** [comment]
Yii: Yes, it is!
