### ISSUE TITLE
Update logo in readme to transparent

### ISSUE THREAD

**Issue by vjik** [yiisoft/yii-demo#253]
Now in dark theme logo looks bad.

![image](https://user-images.githubusercontent.com/525501/109422142-5711ec80-79eb-11eb-94e9-47014ea4b49b.png)

**Comment by samdark** [comment]
https://www.yiiframework.com/logo

**Comment by AndreyPootMay** [comment]
Can I assign me this task?

**Comment by samdark** [comment]
@AndreyPootMay sure. Done.

**Comment by AndreyPootMay** [comment]
Assigned and pull request pushed, waiting for merge and check, thanks from México
