### ISSUE TITLE
Errors not logged

### ISSUE THREAD

**Issue by Nex-Otaku** [yiisoft/yii-demo#255]
Application does not log errors.

Update 2021-03-16:
Web application with disabled SQlite PHP extension throws error that is not logged.
Console application does not log error on any exception.

### What steps will reproduce the problem?

Throw any exception in application code, for example \RuntimeException

### What is the expected result?

Error appears in log file: /runtime/logs/app.log

### What do you get instead?

No errors in log

### Additional info

1. Errors are not logged in both console and web. 

2. In Yii2 basic application, application errors are logged by default.

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 7.4
| Operating system | WSL

**Comment by devanych** [comment]
Checked, all errors are logged out of the box. Please check your logger configuration.

**Comment by Nex-Otaku** [comment]
@devanych no changes made to configuration, clean demo install.

**Comment by devanych** [comment]
Very strange :)

If I have logs, and you do not, then this is not a logger's problem. Maybe the problem is the rights to the runtime folder, you could try changing the rights to 0777 and try again?

**Comment by Nex-Otaku** [comment]
@devanych no problems with folders, code just doesnt get executed.

**Comment by Nex-Otaku** [comment]
@devanych make a clean app install and check.

**Comment by BoShurik** [comment]
Can't reproduce
```php
// \App\Controller\SiteController
public function index(): ResponseInterface
{
    throw new \RuntimeException('test');

    return $this->viewRenderer->render('index');
}
```

produces in `runtime/logs/app.log`
```
2021-03-09 11:52:25.253000 [error][application] RuntimeException with message 'test' 
```

**Comment by devanych** [comment]
@Nex-Otaku I also have everything working correctly, as well as @BoShurik. Both on localhost and in docker.

**Comment by samdark** [comment]
That should be something very specific to @Nex-Otaku environment. I'm afraid we can't fix it since we have no such environment. @Nex-Otaku in case you'll find out the details, let us know.

**Comment by Nex-Otaku** [comment]
Experimented with it a bit. 

Application does log errors in web mode, but not in all cases, and does not log errors in console mode at all.

Steps to reproduce on Ubuntu 20.04, PHP 7.4 (WSL).


**Web:**

1. Install clean new demo app
composer create-project --prefer-dist --stability=dev yiisoft/yii-demo yii3-demo-logging-errors
cd yii3-demo-logging-errors

2. Turn off pdo_sqlite
sudo phpdismod pdo_sqlite

3. Restart FPM
sudo service php7.4-fpm restart

4. Run app (kill it and restart if already running)
composer run serve > ./runtime/yii.log 2>&1 &

5. Check blog page response, should give 500 because SQlite is disabled.
curl -s -i http://127.0.0.1:8080/blog | head -1

6. Check logs in runtime/app.log - no errors there!



**Console:**

1. Install clean new demo app
composer create-project --prefer-dist --stability=dev yiisoft/yii-demo yii3-demo-logging-errors
cd yii3-demo-logging-errors

2. Add exception to App\Command\Router\ListCommand::execute()
throw new \RuntimeException("You would not see that in log");

3. Run console command
vendor/bin/yii router/list

4. See error message in console output...

5. But not in log! runtime/app.log

**Comment by samdark** [comment]
It happens because Cycle tried to read SQLite schema during container initializaition before fully configured logger replaces initial one:

- https://github.com/yiisoft/yii-demo/blob/master/src/ApplicationRunner.php#L55

**Comment by samdark** [comment]
We've fixed web app case and threre is a separate issue for console: https://github.com/yiisoft/yii-console/issues/110

**Comment by Nex-Otaku** [comment]
Checked web applications, errors are logged correctly to `/runtime/logs/app.log`. Thanks.

**Comment by rustamwin** [comment]
Fixed for console application as well.
