### ISSUE TITLE
Post content should not be HTML encoded on edit form

### ISSUE THREAD

**Issue by dzentota** [yiisoft/yii-demo#265]
### What steps will reproduce the problem?
Create a Post with an HTML code in the `content` field, edit created Post

### What is the expected result?
raw HTML code (unencoded)

### What do you get instead?
HTML-encoded content

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 
| Operating system |

**Comment by samdark** [comment]
Fixed. Thanks.
