### ISSUE TITLE
Misleading README.md

### ISSUE THREAD

**Issue by dzentota** [yiisoft/yii-demo#267]
Installation step 4 says:

> If you want to disable this behavior then `comment out line with Generator\SyncTables::class in the config/params.php`.

while the whole contents of the `config/params.php` is:

```php
<?php

declare(strict_types=1);

return [
    'mailer' => [
        'adminEmail' => 'admin@example.com',
    ],
];
```

**Comment by samdark** [comment]
Fixed.
