### ISSUE TITLE
JQ已经是过去时代 期待希望3.0给我们惊艳，更易于和Vue 或 react 现代前端框架 结合  

### ISSUE THREAD

**Issue by admiao** [yiisoft/yii-demo#27]
JQ已经是过去时代 期待希望3.0给我们惊艳，更易于和Vue 或 react 现代前端框架 结合

**Comment by samdark** [comment]
Correct. There will be no jQuery out of the box. We're not integrating any JavaScript framework in any of the primary packages so it's easy to choose one for your project.
