### ISSUE TITLE
Call to undefined method  `validate`

### ISSUE THREAD

**Issue by dzentota** [yiisoft/yii-demo#270]
### What steps will reproduce the problem?

- Add new Post
- Edit created Post

### What is the expected result?

The post has been successfully updated

### What do you get instead?

Error `Call to undefined method `

### Additional info

https://github.com/yiisoft/yii-demo/blob/815bb6dcda44f7b095a6f32bdfd3162c6c839f8b/src/Blog/Post/PostController.php#L94

There should be `$validator->validate($form)` instead of `$form->validate($validator)`

```php
if ($form->load($body) && $validator->validate($form)->isValid()) {
```

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 
| Operating system |

**Comment by samdark** [comment]
Fixed. Thanks.
