### ISSUE TITLE
This project vs the other yii3 project templates

### ISSUE THREAD

**Issue by developedsoftware** [yiisoft/yii-demo#41]
Hi @samdark,

I realise yii3 isnt finished yet and is subject to change, but I was wondering if there was an agreed project layout to use as of yet? Is it something like this project structure or should I be using the structure similar to yii2 found here https://github.com/yiisoft/yii-base-web

yii-base-web looks more familiar to me - but yii-demo is a pinned repo and has recent commits (suggesting that is the one to use). 

Being Jan 2020 I thought I would take the plunge with yii3 as its nearing release - but want to make sure I start on the right path...

**Comment by samdark** [comment]
@developedsoftware demo is the current one. Templates aren't ready yet.
