### ISSUE TITLE
Update docker-compose.yml

### ISSUE THREAD

**Issue by xepozz** [yiisoft/yii-demo#46]

**Comment by samdark** [comment]
What should be updated exactly?

**Comment by xepozz** [comment]
At now it's not working. Would be nice to fix it :)

**Comment by samdark** [comment]
How exactly it's not working?

**Comment by xepozz** [comment]
Hmm...it works now, but yesterday it didn’t want to work. I had errors with sqlite driver.

**Comment by xepozz** [comment]
Ok then, why *.local file are commited instead of just docker-compose.yml? *.local keeps user's overrides over not *.local file.

**Comment by samdark** [comment]
@hiqsol am I correct that it's just a convention for local development config?

**Comment by samdark** [comment]
Yes. Above is correct.

**Comment by samdark** [comment]
So, it seems there's nothing to fix, right?
