### ISSUE TITLE
Change behaviour of `render` method

### ISSUE THREAD

**Issue by xepozz** [yiisoft/yii-demo#52]
### What steps will reproduce the problem?
Using `render` function to render content of view file looks too hard.
Instead of return the result of `render` function we should to create response before and write data after.
Let's delegate creating the `Response` object to `render` function. 

### What is the expected result?
User controllers will be more simpler and cleaner
```php
public function index(): Response
{
    return $this->render('index');
}
```

### What do you get instead?
```php
public function index(): Response
{
    $output = $this->render('index');
    $response = $this->responseFactory->createResponse();
    $response->getBody()->write($output);
    return $response;
}
```

**Comment by samdark** [comment]
View component is not aware of request-response. Its job is rendering templates. I don't think it's a good idea to couple it like suggested.

Still, I agree that it looks a bit cumbersome to create response like that (while it makes perfect sense if redirect or sending headers is involved).

Possible solutions:

1. Allow returning strings from handlers (actions).
2. Provide a shortcut method like createResponseWithBody($string).
3. ???

**Comment by xepozz** [comment]
If you want to render and collect result to string you can use `$this->getView()->render(...);`
`Controller::render()` is only wrapper over `$view->render`. I do not see any problems in returning  `Response`

Moreover, such a template is familiar to all PHP developers (at least), because all frameworks provide such a convenient interface.

**Comment by samdark** [comment]
Returning response directly from `render()`? Some references would not hurt...

**Comment by yiiliveext** [comment]
I think @xepozz mean something like this
```php
//abstract class Controller
protected function render(string $view, array $parameters = []): string
{
    $response = $this->responseFactory->createResponse();
    $content = $this->view->render($view, $parameters, $this);
    
    return $response->getBody()->write($this->renderContent($content));
}
```

**Comment by samdark** [comment]
Yes but that would be:

```php
protected function render(string $view, array $parameters = []): Response
```

**Comment by yiiliveext** [comment]
> Yes but that would be:
> 

Of course, I've just forgotten to change after copying.

**Comment by samdark** [comment]
Thought more about it. It doesn't sound bad to do it.
