### ISSUE TITLE
Class 'Yiisoft\\Router\\FastRoute\\FastRouteFactory' not found

### ISSUE THREAD

**Issue by arizanovj** [yiisoft/yii-demo#55]
### What steps will reproduce the problem?
Clone the demo project, run composer install and open it through web server (apache). 
### What is the expected result?
Functional demo project.
### What do you get instead?

PHP Fatal error:  Uncaught Error: Class 'Yiisoft\\Router\\FastRoute\\FastRouteFactory' not found in /var/www/html/yii-demo-master/src/Factory/AppRouterFactory.php:71\nStack trace:\n#0 /var/www/html/yii-demo-master/vendor/yiisoft/factory/src/Definitions/CallableDefinition.php(19): App\\Factory\\AppRouterFactory->__invoke()\n#1 /var/www/html/yii-demo-master/vendor/yiisoft/di/src/Container.php(134): Yiisoft\\Factory\\Definitions\\CallableDefinition->resolve()\n#2 /var/www/html/yii-demo-master/vendor/yiisoft/di/src/Container.php(114): Yiisoft\\Di\\Container->buildInternal()\n#3 /var/www/html/yii-demo-master/vendor/yiisoft/di/src/Container.php(80): Yiisoft\\Di\\Container->build()\n#4 /var/www/html/yii-demo-master/vendor/yiisoft/factory/src/Definitions/Reference.php(44): Yiisoft\\Di\\Container->get()\n#5 /var/www/html/yii-demo-master/vendor/yiisoft/di/src/Container.php(134): Yiisoft\\Factory\\Definitions\\Reference->resolve()\n#6 /var/www/html/yii-demo-master/vendor/yiisoft/di/src/Container.php(114): Yiisoft\\Di\\Container->buildInternal()\n#7 /var/www/html/yi in /var/www/html/yii-demo-master/src/Factory/AppRouterFactory.php on line 71

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 
| Operating system |

**Comment by yiiliveext** [comment]
You have to change your config as mentoined here

**Comment by samdark** [comment]
Fixed in master. You can now pull and do composer update.
