### ISSUE TITLE
Error adding sample data

### ISSUE THREAD

**Issue by armpogart** [yiisoft/yii-demo#62]
### What steps will reproduce the problem?
After installing and configuring demo (with sqlite) without changing anything, running `vendor\bin yii fixture/add 20` produces error.

### What is the expected result?
Fixture to add random data.

### What do you get instead?
`[ERROR] Maximum function nesting level of '256' reached, aborting!`

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 7.4.3
| Operating system | Win 10 x64

`yii fixture/add 10` is working ok. The error comes from Cycle ORM mapper and it's dependency `zendframework/zend-hydrator`. Exception is thrown on this [line](https://github.com/yiisoft/yii-demo/blob/48d0db0a75ef801be1033f23a5add94da1c86851/src/Command/Fixture/AddCommand.php#L65) from yii code.
I will debug it further and open issue on Cycle repository also.

**Comment by roxblnfk** [comment]
I could not reproduce

| Q                | A
| ---------------- | ---
| PHP version      | 7.4.3
| Operating system | Win 10 x64

`yii fixture/add 20` mySQL - ok, SQLite - ok
`yii fixture/add 50` mySQL - ok, SQLite - ok

**Comment by armpogart** [comment]
I've found the reason for the issue. `xdebug` extension has maximum level of function nesting, which can be increased (which is 256 by default). See this [issue](https://github.com/zircote/swagger-php/issues/445). Disabling `xdebug` fixed the problem.
You can reproduce the problem enabling xdebug for `php-cli`. It is always enabled in my case as I extensively debug also command line php.

Feel free to close the issue, or keep it open if you think there is a need to add a note somewhere.
