### ISSUE TITLE
Material Design Support

### ISSUE THREAD

**Issue by TNSaturday** [yiisoft/yii-demo#64]
Rather than an issue this one is more feauture request. Yii2 is shipped with Bootstrap 3 as an UI framework. I see, that you add Bootstrap 4 as one of the possible templates. Are there any plans on native Material Design framework support?

**Comment by samdark** [comment]
Move to demo repo for now.

@TNSaturday for now there's no such plan. Template would be shipped with one of the popular frameworks. For now, Bootstrap 4 and Tailwind are candidates.
