### ISSUE TITLE
Add aliases config to container

### ISSUE THREAD

**Issue by armpogart** [yiisoft/yii-demo#68]
First of all it is not obvious where `Aliases` is coming from, I mean when doing `$container->get(Aliases::class)`. As I've checked I see that it is configured in `yii-web` di container, but I think it is not obvious and we still need to add it to `yii-demo`s common config (actually that config is supposed to be in base template, but as I understand `yii-web` is not a template and `yii-demo` is just a demo showing yii3 for the time being).

Now when I add `Aliases` config to this projects common config:
```php
Aliases::class => [
    '__class' => Aliases::class,
    '__construct' => [$params['aliases']],
],
```
I get wrong config built by [`composer-config-plugin`](https://github.com/hiqdev/composer-config-plugin), the config built looks like this in runtime directory:
```php
'Yiisoft\\Aliases\\Aliases' => [
    '__class' => 'Yiisoft\\Aliases\\Aliases',
    '__construct()' => [
        [
            '@root' => 'D:\\dev\\php\\tuninfo',
            '@vendor' => '@root/vendor',
            '@public' => '@root/public',
            '@runtime' => '@root/runtime',
            '@bower' => '@vendor/bower-asset',
            '@npm' => '@vendor/npm-asset',
            '@web' => '/',
        ],
    ],
    '__construct' => [
        [
            '@root' => 'D:\\dev\\php\\tuninfo',
            '@vendor' => '@root/vendor',
            '@public' => '@root/public',
            '@runtime' => '@root/runtime',
            '@bower' => '@vendor/bower-asset',
            '@npm' => '@vendor/npm-asset',
            '@web' => '/',
        ],
    ],
],
```
and I get following error `Argument 2 passed to Yiisoft\Aliases\Aliases::__set() must be of the type string, array given in vendor\yiisoft\aliases\src\Aliases.php on line 27`.

As the point 1 refers to this project I've opened the issue here, though I see that the wrong config is the issue in `composer-config-plugin`.

**Comment by roxblnfk** [comment]
The current implementation implies that you will specify aliases in the `params.php`

**Comment by armpogart** [comment]
For the first point I'm sure you agree that `composer-config-plugin` incorrectly merges configs (not sure what will be correct way, to replace definition of the constructor or to merge constructor parameter if it is array, maybe the first will be more correct).

@roxblnfk Yes, but the word `implies` here is the same as it is defined in `yii-web` container. What if I just want to override definition (e.g. mocking for testing purposes).

Isn't the purpose of container to define concrete class (implementation) used in runtime?

**Comment by armpogart** [comment]
Isn't the purpose of using DI container to avoid unnecessary magic implied by the framework?
If the current implementation just implies that you will specify aliases in `params.php` and Aliases class will be used anyway, than I don't get why `yiisoft/aliases` is separate package and not just bundled in `yii-web` or somewhere else.

**Comment by roxblnfk** [comment]
If you want to redefine the Aliases class in the container, then try to fix your definition code

```php
Aliases::class => [
    '__class' => Aliases::class,
    '__construct()' => [$params['aliases']],
],
```

**Comment by samdark** [comment]
It should be `__construct()` with `()`.

**Comment by armpogart** [comment]
@roxblnfk Oops, sorry and thanks. But my first point I think still stands.

**Comment by roxblnfk** [comment]
https://trello.com/c/3lfjzZKt/31-remove-composer-config-plugin
