### ISSUE TITLE
CSRF fails after relogin

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii-demo#77]
1. Login.
2. Logout.
3. Try to login again.

Expected to log in. Got CSRF protection responding with "Unprocessable entity".

**Comment by iTiaNex** [comment]
the session or $this->session->get(''_csrf") was flushed after login

**Comment by samdark** [comment]
Seems PHPSESSID cookie keeps its value after logout. If it's deleted, it works well.

**Comment by samdark** [comment]
Likely `Session::destroy()` is missing something.

**Comment by rustamwin** [comment]
It looks like `SessionMiddleware` is not working properly after yiisoft/yii-web@4876355e6a3cf220eb281d49768aa7ac1921f792

**Comment by samdark** [comment]
Likely.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii-web/pull/240

**Comment by TianNex** [comment]
thank you
