### ISSUE TITLE
where is the ORMInterface $orm in BlogController come from

### ISSUE THREAD

**Issue by dvaknheo** [yiisoft/yii-demo#81]
I just begin to read the demo code , for select a better  framework.
run the code work well, show the result ok.

http://127.0.0.1:8080/blog

Tracing code at src/Blog/BlogController
```php
    public function index(Request $request, ORMInterface $orm, ArchiveRepository $archiveRepo): Response
    {
var_dump(get_class($orm)); // => Cycle\ORM\ORM
        /** @var PostRepository $postRepo */
        $postRepo = $orm->getRepository(Post::class);
debug_print_backtrace(2); 
       //...
    }
```
what the $orm come from ?  can  I have other way to get it.
like  $orm = App::GetOrm();  
and  where the code is $orm object init ?

i want to that what my object is decleare explict.

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 7.4.4
| Operating system | wsl1-debian

**Comment by samdark** [comment]
It's different from Yii 1.1 and Yii 2. Here's how it works: https://github.com/yiisoft/docs/blob/master/guide/en/concept/di-container.md
