### ISSUE TITLE
Не работает демо

### ISSUE THREAD

**Issue by Gustik** [yiisoft/yii-demo#82]
в пакете `yiisoft/composer-config-plugin-output `в файле `web.php` переменная
`$baseDir = dirname(__DIR__, 3); `
перезаписывается из `dotenv.php` на 
`$baseDir = __DIR__;`
итого,  установленное приложение  ищет папки не из корня приложения, а с `корень-приложения/runtime/build/config`

**Comment by samdark** [comment]
Попробуйте ещё раз. Скорее всего поправлено: https://github.com/yiisoft/composer-config-plugin/issues/19
