### ISSUE TITLE
Getting DI Container

### ISSUE THREAD

**Issue by freekup** [yiisoft/yii-demo#97]
Is there a way to get the DI container from dependency injection without initializing it from the constructor? What I mean is like Laravel which has a `resolve` function to get container without initializing it from the constructor.

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 7.4
| Operating system | Windows 10

**Comment by samdark** [comment]
Why do you need container instance?

**Comment by freekup** [comment]
I have a parent class that is used by many other classes. This parent class uses a DI Container for use by child classes. I don't want to initialize it repeatedly in the child constructor. If I use Laravel, I can call the `resolve` function to get the DI Container without initializing it repeatedly in the child class.

**Comment by samdark** [comment]
Why do you need an instance of DI container in this parent class? Can't it explicitly require services it actually needs?

**Comment by freekup** [comment]
I will show you the code that I mean.

This is my parent class. This class will be used by many other classes.
```php
class Service
{
    protected RequestHelper $requestHelper;

    /**
     * Service constructor.
     * @param RequestHelper $requestHelper
     * @param Validator $validator
     */
    public function __construct(RequestHelper $requestHelper, Validator $validator)
    {
        $this->validator = $validator;
        $this->requestHelper = $requestHelper;
    }
}
```

And this is one of the child classes that use the `Service` class.
```php
class BasicInformationService extends Service
{
    /**
     * CheckAvailabilityService constructor.
     * @param RequestHelper $requestHelper
     * @param BasicInformationValidator $validator
     */
    public function __construct(RequestHelper $requestHelper, BasicInformationValidator $validator)
    {
        parent::__construct($requestHelper, $validator);
    }
}
```

I don't want to pass the RequestHelper interface repeatedly in every class that uses class `Service`. If I use Laravel, I can do it like this. So I don't need to pass RequestHelper interface repeatedly in every class that uses class `Service`

```php
class Service
{
    protected RequestHelper $requestHelper;

    /**
     * Service constructor.
     * @param RequestHelper $requestHelper
     * @param Validator $validator
     */
    public function __construct(RequestHelper $requestHelper, Validator $validator)
    {
        $this->validator = $validator;
        $this->requestHelper = resolve(RequestHelper::class);
    }
}

```

**Comment by freekup** [comment]
I just outsmarted it by adding a function to the file in `src/functions.php` like this

```php
if(!function_exists('resolve')) {
    /**
     * To getting DI Container globally
     * 
     * @param string $id
     * @return mixed|object
     * @throws \Yiisoft\Factory\Exceptions\CircularReferenceException
     * @throws \Yiisoft\Factory\Exceptions\InvalidConfigException
     * @throws \Yiisoft\Factory\Exceptions\NotFoundException
     * @throws \Yiisoft\Factory\Exceptions\NotInstantiableException
     */
    function resolve(string $id)
    {
        global $container;

        return $container->get($id);
    }
}
```

**Comment by rustamwin** [comment]
Similar to yiisoft/di#99?

**Comment by samdark** [comment]
Yeah. I tend not to add that to the framework since it has too many drawbacks:

1. Dependencies are becoming implicit.
2. Implementation becomes tied to container/framework.

But I'll leave the issue opened for discussion to see if more people want this feature.

**Comment by terabytesoftw** [comment]
If you add the resolver function, we basically make the container a service locator, for me it is a global static, it shouldn't be.

**Comment by Nex-Otaku** [comment]
Looks like poor design that stimulates to resolving dependencies SL-style. 

Why do you have to override constructor? This code example is too abstract. I can't figure out why it should look like this. Guess it can be done in more clean and easy way.

Maybe code in RequestHelper should be moved entirely to Service? No need for a dependency then.

**Comment by samdark** [comment]
Won't be implemented for the reasons given in https://github.com/yiisoft/yii-demo/issues/97#issuecomment-625490568
